email: sanjai.ramesh@gmail.com

baseurl: ""
url: "https://sanjairamesh.github.io"

theme: minima

author:
  name: Ramesh Boopathi
minima:
  skin: classic  
linkedin_username: ramesh-boopathi-7a840130
github_username: SanjaiRamesh

markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

header_pages:
  - projects.md
  - architecture.md
show_excerpts: true

collections:
  projects:
    output: true
    permalink: /projects/:name/
  architecture:
    output: true
    permalink: /architecture/:name/
  leadership:
    output: true
    permalink: /leadership/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "projects"
    values:
      layout: page
  - scope:
      path: ""
      type: "architecture"
    values:
      layout: page
  - scope:
      path: ""
      type: "leadership"
    values:
      layout: page

plugins:
  - jekyll-feed
  - jekyll-seo-tag